export const guests = {
 1:["Luci De Barrios ","Amada",2,1],
 2:["Irama De Herrera ","Querida",5,1],
 3:["Nakari Cabezas ","Querida",5,1],
 4:["Karina Barrios","Querida",3,1],
 5:["Carolina De Moreno","Querida",4,1],
 6:["Ramón Marin","Querido",1,0],
 7:["Yosneidi Marin","Querida",2,1],
 8:["Yosibeth Marin ","Querida",2,1],
 9:["Abraham Centeno ","Amado",3,1],
 10:["Raul Centeno ","Querido",2,1],
 11:["Yudeisi Valles ","Estimada",2,1],
 12:["Roxana Centeno ","Querida",2,1],
 13:["Leidy Barrios ","Querida",3,1],
 14:["Escarly Arevalo","Querida",2,1],
 15:["Katty Cardenas ","Querida",2,1],
 16:["Andrés González ","Querido",3,1],
 17:["Niurka Cardenas","Querida",2,1],
 18:["Melvi De Suárez ","Querida",3,1],
 19:["Anyelin Parra","Amada",3,1],
 20:["Roseline Parra","Amada",3,1],
 21:["Rosmery Parra","Amada",4,1],
 22:["Yoseline Parra","Amada",3,1],
 23:["Yoseikelin Parra","Amada",2,1],
 24:["Luisa De Parra","Amada",1,0],
 25:["Petra Hernández","Amada",1,1],
 26:["Alejandro Rojas","Querido",2,1],
 27:["Waimar Rojas","Querido",2,1],
 28:["Franklin Chacón","Querido",2,1],
 29:["Franyeli Chacón","Querida",2,1],
 30:["Yeni Chacon","Querida",2,1],
 31:["Luisa Chacon","Querida",2,1],
 32:["Adriani Bamondez","Querida",2,1],
 33:["Fermin Gutiérrez","Estimado",2,1],
 34:["Carlos García","Estimado",2,1],
 35:["Daniel Briceño","Estimado",2,1],
 36:["Álvaro Melchor","Estimado",2,1],
 37:["Fermin Gutiérrez Jr.","Estimado",2,1],
 38:["Ana y  Chelín ","Queridos",2,2],
 39:["Fredy Valencia","Estimado",2,1],
 40:["Martha Escorcia","Querida",3,1],
 41:["Luis Astudillo","Querido",2,1],
 42:["Francia Parra","Amada",3,1],
 43:["SUNEP Miranda","Queridos",4,1],
 44:["Pastores Juan y Pedro","Queridos",2,1],
}

